/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteImport } from './routes/_sidebar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidebarPoliciesRouteImport } from './routes/_sidebar/policies'
import { Route as SidebarOptimizationRouteImport } from './routes/_sidebar/optimization'
import { Route as SidebarLiveMetricsRouteImport } from './routes/_sidebar/live-metrics'
import { Route as SidebarClustersIndexRouteImport } from './routes/_sidebar/clusters/index'
import { Route as SidebarClustersClusterIdRouteImport } from './routes/_sidebar/clusters/$clusterId'

const SidebarRoute = SidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarPoliciesRoute = SidebarPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarOptimizationRoute = SidebarOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarLiveMetricsRoute = SidebarLiveMetricsRouteImport.update({
  id: '/live-metrics',
  path: '/live-metrics',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarClustersIndexRoute = SidebarClustersIndexRouteImport.update({
  id: '/clusters/',
  path: '/clusters/',
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarClustersClusterIdRoute =
  SidebarClustersClusterIdRouteImport.update({
    id: '/clusters/$clusterId',
    path: '/clusters/$clusterId',
    getParentRoute: () => SidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-metrics': typeof SidebarLiveMetricsRoute
  '/optimization': typeof SidebarOptimizationRoute
  '/policies': typeof SidebarPoliciesRoute
  '/clusters/$clusterId': typeof SidebarClustersClusterIdRoute
  '/clusters/': typeof SidebarClustersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-metrics': typeof SidebarLiveMetricsRoute
  '/optimization': typeof SidebarOptimizationRoute
  '/policies': typeof SidebarPoliciesRoute
  '/clusters/$clusterId': typeof SidebarClustersClusterIdRoute
  '/clusters': typeof SidebarClustersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/_sidebar/live-metrics': typeof SidebarLiveMetricsRoute
  '/_sidebar/optimization': typeof SidebarOptimizationRoute
  '/_sidebar/policies': typeof SidebarPoliciesRoute
  '/_sidebar/clusters/$clusterId': typeof SidebarClustersClusterIdRoute
  '/_sidebar/clusters/': typeof SidebarClustersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live-metrics'
    | '/optimization'
    | '/policies'
    | '/clusters/$clusterId'
    | '/clusters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live-metrics'
    | '/optimization'
    | '/policies'
    | '/clusters/$clusterId'
    | '/clusters'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/live-metrics'
    | '/_sidebar/optimization'
    | '/_sidebar/policies'
    | '/_sidebar/clusters/$clusterId'
    | '/_sidebar/clusters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRoute: typeof SidebarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/policies': {
      id: '/_sidebar/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof SidebarPoliciesRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/optimization': {
      id: '/_sidebar/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof SidebarOptimizationRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/live-metrics': {
      id: '/_sidebar/live-metrics'
      path: '/live-metrics'
      fullPath: '/live-metrics'
      preLoaderRoute: typeof SidebarLiveMetricsRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/clusters/': {
      id: '/_sidebar/clusters/'
      path: '/clusters'
      fullPath: '/clusters/'
      preLoaderRoute: typeof SidebarClustersIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    '/_sidebar/clusters/$clusterId': {
      id: '/_sidebar/clusters/$clusterId'
      path: '/clusters/$clusterId'
      fullPath: '/clusters/$clusterId'
      preLoaderRoute: typeof SidebarClustersClusterIdRouteImport
      parentRoute: typeof SidebarRoute
    }
  }
}

interface SidebarRouteChildren {
  SidebarLiveMetricsRoute: typeof SidebarLiveMetricsRoute
  SidebarOptimizationRoute: typeof SidebarOptimizationRoute
  SidebarPoliciesRoute: typeof SidebarPoliciesRoute
  SidebarClustersClusterIdRoute: typeof SidebarClustersClusterIdRoute
  SidebarClustersIndexRoute: typeof SidebarClustersIndexRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarLiveMetricsRoute: SidebarLiveMetricsRoute,
  SidebarOptimizationRoute: SidebarOptimizationRoute,
  SidebarPoliciesRoute: SidebarPoliciesRoute,
  SidebarClustersClusterIdRoute: SidebarClustersClusterIdRoute,
  SidebarClustersIndexRoute: SidebarClustersIndexRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRoute: SidebarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
